<template>
<section class="national-alarm-panel" aria-labelledby="national-alarm-title" tabindex="-1">
 <header><div><h2 id="national-alarm-title">气象预警</h2><p>数据时间：{{ formatNationalAlarmTime(snapshot?.fetchedAt) }}</p></div><div><button type="button" :disabled="phase==='loading'||phase==='refreshing'" :aria-label="phase==='refreshing'?'正在刷新浙江预警':'刷新浙江预警'" @click="emit('refresh')"><span :class="{spinning:phase==='refreshing'}">↻</span></button><button type="button" aria-label="关闭浙江预警" @click="emit('close')">×</button></div></header>
 <div v-if="errorMessage" class="error" role="alert">{{ errorMessage }}</div>
 <p v-else-if="phase==='loading'" class="empty">浙江预警数据加载中…</p>
 <p v-else-if="!items.length" class="empty">当前未查询到浙江省生效预警</p>
 <div v-else class="records" role="list"><button v-for="alarm in items" :key="alarm.id" :ref="(element)=>setRecordEl(alarm.id,element)" type="button" role="listitem" :class="{selected:selection?.id===alarm.id}" :aria-label="`${formatNationalAlarmTime(alarm.issuedAt)}，${alarm.title}，行政代码 ${alarm.adminCode||'未知'}`" @click="emit('select',alarm)"><img v-if="alarm.iconUrl" :src="alarm.iconUrl" alt="" @error="($event.target as HTMLImageElement).style.display='none'"/><span v-else aria-hidden="true">⚠</span><strong>{{ alarm.title }}</strong></button></div>
 <footer>数据来源：中央气象台（NMC）</footer>
</section>
</template>
<script setup lang="ts">
import {computed,nextTick,onMounted,watch} from 'vue';import type {NationalAlarmPhase,NationalAlarmSelection,NationalAlarmSnapshot,NationalWeatherAlarm} from '../../features/national-alarms/nationalAlarmTypes';import {formatNationalAlarmTime,sortNationalAlarms} from '../../features/national-alarms/nationalAlarmSelectors';
const props=defineProps<{phase:NationalAlarmPhase;snapshot:NationalAlarmSnapshot|null;selection:NationalAlarmSelection|null;errorMessage:string}>();const emit=defineEmits<{refresh:[];close:[];select:[alarm:NationalWeatherAlarm]}>();const items=computed(()=>sortNationalAlarms(props.snapshot?.items??[]));const recordEls=new Map<string,HTMLElement>();const setRecordEl=(id:string,element:Element|unknown)=>{if(element instanceof HTMLElement)recordEls.set(id,element);else recordEls.delete(id)};watch(()=>props.selection?.id,(id)=>{if(!id)return;nextTick(()=>recordEls.get(id)?.scrollIntoView({block:'nearest',behavior:'smooth'}))});onMounted(()=>nextTick(()=>document.querySelector<HTMLElement>('.national-alarm-panel')?.focus()));
</script>
<style scoped>
.national-alarm-panel{position:absolute;top:12px;right:12px;z-index:1020;width:360px;height:min(520px,calc(100vh - 320px));display:flex;flex-direction:column;border:1px solid rgba(148,163,184,.34);border-radius:10px;background:rgba(248,250,252,.96);box-shadow:0 6px 20px rgba(15,23,42,.18),0 1px 2px rgba(15,23,42,.12);backdrop-filter:blur(8px);color:#0f172a;outline:0}.national-alarm-panel header{display:flex;justify-content:space-between;gap:8px;padding:10px 12px;border-bottom:1px solid #e2e8f0}.national-alarm-panel h2,.national-alarm-panel p{margin:0}.national-alarm-panel h2{font-size:16px}.national-alarm-panel header p{margin-top:5px;font-size:11px;color:#64748b}footer{font-size:11px;color:#64748b}.national-alarm-panel header button{width:32px;height:32px;border:0;border-radius:7px;background:transparent;color:#475569;font-size:20px;cursor:pointer}.national-alarm-panel header button:hover:not(:disabled){background:#e2e8f0}.national-alarm-panel header button:disabled{cursor:wait}.national-alarm-panel header button span{display:inline-block}.national-alarm-panel header button .spinning{animation:national-alarm-spin .8s linear infinite}@keyframes national-alarm-spin{to{transform:rotate(360deg)}}.records{min-height:0;flex:1;overflow-y:auto;padding:6px}.records button{width:100%;display:grid;grid-template-columns:24px minmax(0,1fr);gap:6px;align-items:center;padding:8px;border:1px solid transparent;border-radius:7px;background:transparent;color:#334155;text-align:left;cursor:pointer}.records button:hover,.records button.selected{border-color:#93c5fd;background:#eff6ff}.records img{width:20px;height:20px;object-fit:contain}.records strong{font-size:12px;line-height:1.45;font-weight:600}.empty,.error{padding:18px 12px;color:#64748b;text-align:center;font-size:12px}.error{color:#991b1b}footer{padding:8px 12px;border-top:1px solid #e2e8f0}@media(max-width:520px){.national-alarm-panel{left:12px;right:12px;width:auto;height:min(520px,calc(100vh - 320px))}}
</style>
