<template>
<section class="weather-popup" :class="kind" :style="positionStyle" role="dialog" :aria-label="kind==='alert'?'天气预警详情':'位置天气详情'" @click.stop>
 <header :style="kind==='alert'?{'--warning':alertColor}:{}"><strong>{{ title }}</strong><button type="button" aria-label="关闭天气浮窗" @click="emit('close')">×</button></header>
 <div class="popup-body">
  <template v-if="kind==='alert'&&alert"><dl class="alert-fields"><div><dt>发布时间</dt><dd>{{formatBeijing(alert.issuedTime)}}</dd></div><div v-if="alert.urgency"><dt>紧迫程度</dt><dd>{{weatherEnumZh(alert.urgency)}}</dd></div><div><dt>严重程度</dt><dd>{{weatherEnumZh(alert.severity)}}</dd></div><div v-if="alert.certainty"><dt>确定性</dt><dd>{{weatherEnumZh(alert.certainty)}}</dd></div></dl><section><h3>预警说明</h3><p>{{alert.description||'--'}}</p></section><section v-if="alert.criteria"><h3>触发标准</h3><p>{{alert.criteria}}</p></section><section v-if="alert.instruction"><h3>防御指南</h3><p>{{alert.instruction}}</p></section></template>
  <template v-else-if="bundle"><section class="current"><h3>当前天气</h3><div v-if="bundle.current.status==='success'&&bundle.current.data" class="current-main"><QWeatherIcon :code="bundle.current.data.condition.code"/><strong>{{bundle.current.data.condition.text||'--'}} {{unitText(bundle.current.data.temperature)}}</strong></div><div v-else-if="bundle.current.status==='error'" class="module-error">实时天气加载失败 <button @click="emit('retry','current')">重试</button></div><dl v-if="bundle.current.data"><div><dt>体感温度</dt><dd>{{unitText(bundle.current.data.feelsLike)}}</dd></div><div><dt>近一小时降水</dt><dd>{{unitText(bundle.current.data.precipitation?.amount)}}</dd></div><div><dt>降水强度</dt><dd>{{unitText(bundle.current.data.precipitation?.intensity)}}</dd></div><div><dt>降水类型</dt><dd>{{precipitationType(bundle.current.data.precipitation?.type)}}</dd></div><div><dt>湿度</dt><dd>{{percentage(bundle.current.data.humidity)}}</dd></div></dl><small>观测时间 {{formatBeijing(bundle.current.data?.observationTime)}}</small></section>
   <section class="minutely"><h3>未来两小时降水 <small>每 5 分钟</small></h3><div v-if="minutelyKind==='error'" class="module-error">未来两小时降水加载失败 <button @click="emit('retry','minutely')">重试</button></div><p v-else-if="minutelyKind==='empty'">当前查询位置暂无分钟级降水预报</p><template v-else-if="bundle.minutely.data"><p>{{bundle.minutely.data.summary||'暂无降水摘要'}}</p><small>更新于 {{formatBeijing(bundle.minutely.data.updateTime,false)}}</small><div class="rain-legend"><span v-for="type in precipTypes" :key="type">{{precipitationType(type)}}</span></div><div class="bars" role="list" :aria-label="minuteA11y"><button v-for="item in bundle.minutely.data.minutely" :key="item.fxTime" type="button" role="listitem" :aria-label="`${formatBeijing(item.fxTime,false)}，5分钟累计${item.precip}毫米，${precipitationType(item.type)}`" :title="`${formatBeijing(item.fxTime,false)} ${item.precip} mm ${precipitationType(item.type)}`"><i :class="item.type||'other'" :style="{height:`${barHeight(item.precip)}%`}"></i></button></div><div class="minute-axis"><time v-for="index in minuteTicks" :key="index">{{formatBeijing(bundle.minutely.data.minutely[index]?.fxTime,false)}}</time></div><p v-if="minutelyKind==='zero'" class="zero">未来两小时暂无降水</p></template></section>
   <section class="hourly"><h3>未来 24 小时预报 <small>每小时</small><em v-if="hourly.incomplete">数据不完整：共 {{hourly.items.length}} 个时点</em></h3><div v-if="bundle.hourly.status==='error'||!hourly.items.length" class="module-error">未来 24 小时预报加载失败 <button @click="emit('retry','hourly')">重试</button></div><div v-else ref="hours" class="hour-strip" tabindex="0" aria-label="未来24小时天气，可使用左右方向键浏览" @keydown.left.prevent="scrollHours(-1)" @keydown.right.prevent="scrollHours(1)" @wheel="onHourWheel"><article v-for="(item,index) in hourly.items" :key="`${item.forecastTime}-${index}`"><time>{{hourLabel(item.forecastTime,index)}}</time><QWeatherIcon :code="item.condition.code"/><strong>{{item.condition.text||'--'}}</strong><b>{{unitText(item.temperature)}}</b><span>降水 {{percentage(item.precipitation?.probability)}}</span><span>{{unitText(item.precipitation?.amount)}}</span></article></div></section>
   <p class="responsibility">天气数据约为 1 公里分辨率的查询点附近信息，仅供风险辅助判断，不代表整块地块或整个行政区域的实测结果，不作为定损或理赔依据。</p><div class="refer"><span v-for="a in bundle.attributions" :key="`${a.name}-${a.url}`">{{a.name}}</span><span v-for="s in bundle.minutely.data?.refer.sources||[]" :key="s">{{s}}</span><span v-for="l in bundle.minutely.data?.refer.license||[]" :key="l">{{l}}</span></div>
  </template>
 </div>
</section>
</template>
<script setup lang="ts">
import {computed,ref} from 'vue';import type {WeatherAlert,WeatherBundle} from '../../features/weather/weatherTypes';import {formatBeijing,hourlyCards,minutelyState,percentage,precipitationType,unitText,warningColor,weatherEnumZh} from '../../features/weather/weatherAdapter';import QWeatherIcon from './QWeatherIcon.vue'
const props=defineProps<{kind:'alert'|'location';title:string;bundle?:WeatherBundle|null;alert?:WeatherAlert|null;x:number;y:number}>();const emit=defineEmits<{close:[];retry:[module:'current'|'minutely'|'hourly']}>();const hours=ref<HTMLElement|null>(null);const positionStyle=computed(()=>({left:`clamp(12px, ${props.x}px, calc(100% - 372px))`,top:`clamp(58px, ${props.y}px, calc(100% - 200px))`}));const alertColor=computed(()=>props.alert?warningColor(props.alert):'#64748b');const minutelyKind=computed(()=>props.bundle?minutelyState(props.bundle.minutely):'empty');const hourly=computed(()=>props.bundle?hourlyCards(props.bundle.hourly):{items:[],incomplete:false});const precipTypes=computed(()=>[...new Set(props.bundle?.minutely.data?.minutely.map(i=>i.type||'other')||[])]);const minuteTicks=computed(()=>{const n=props.bundle?.minutely.data?.minutely.length||0;if(!n)return[];return[0,Math.round((n-1)*.25),Math.round((n-1)*.5),Math.round((n-1)*.75),n-1]});const minuteA11y=computed(()=>`未来两小时实际返回 ${props.bundle?.minutely.data?.minutely.length||0} 个时点`);const maxPrecip=computed(()=>Math.max(0,...(props.bundle?.minutely.data?.minutely.map(i=>i.precip)||[])));function barHeight(v:number){return v===0?0:Math.max(8,v/(maxPrecip.value||1)*100)}function hourLabel(v:string,index:number){const d=new Date(v),first=new Date(hourly.value.items[0]?.forecastTime||v);const time=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false}).format(d);if(index===0)return time;const day=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',day:'2-digit'}).format(d),firstDay=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',day:'2-digit'}).format(first);return day!==firstDay?`明天 ${time}`:time}function scrollHours(dir:number){hours.value?.scrollBy({left:dir*180,behavior:'smooth'})}function onHourWheel(e:WheelEvent){if(!hours.value||Math.abs(e.deltaY)<=Math.abs(e.deltaX))return;const can=e.deltaY>0?hours.value.scrollLeft+hours.value.clientWidth<hours.value.scrollWidth:hours.value.scrollLeft>0;if(can){e.preventDefault();hours.value.scrollLeft+=e.deltaY}}
</script>
<style scoped>
.weather-popup{position:absolute;z-index:1040;width:360px;max-height:min(640px,calc(100vh - 72px));display:flex;flex-direction:column;border:1px solid rgba(148,163,184,.45);border-radius:10px;background:#fff;box-shadow:0 12px 30px rgba(15,23,42,.25);transform:translate(-50%,-100%);color:#0f172a}.weather-popup>header{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:9px 11px;border-radius:9px 9px 0 0;background:#f8fafc}.weather-popup.alert>header{background:var(--warning);color:#fff}.weather-popup header button{border:0;background:transparent;color:inherit;font-size:20px;cursor:pointer}.popup-body{overflow:auto;padding:10px}.popup-body section+section{margin-top:12px;padding-top:12px;border-top:1px solid #e2e8f0}.popup-body h3,.popup-body p{margin:0 0 6px}.popup-body h3{font-size:13px}.popup-body h3 small{font-weight:500;color:#64748b}.popup-body h3 em{display:block;color:#b45309;font-size:10px;font-style:normal}.popup-body p{white-space:pre-wrap;font-size:12px;line-height:1.55}.alert-fields,.current dl{display:grid;gap:5px;margin:0 0 10px}.alert-fields div,.current dl div{display:grid;grid-template-columns:90px 1fr;gap:8px;font-size:12px}.alert-fields dt,.current dt{color:#64748b}.alert-fields dd,.current dd{margin:0;font-variant-numeric:tabular-nums}.current-main{display:flex;align-items:center;gap:8px;margin:8px 0;font-size:18px}.module-error{display:flex;justify-content:space-between;align-items:center;padding:8px;border-radius:7px;background:#fef2f2;color:#991b1b;font-size:12px}.module-error button{border:0;border-radius:5px;background:#b91c1c;color:#fff;cursor:pointer}.rain-legend{display:flex;gap:8px;margin:6px 0;font-size:10px;color:#64748b}.bars{height:92px;display:flex;align-items:flex-end;gap:2px;border-bottom:1px solid #94a3b8;overflow:hidden}.bars button{flex:1;height:100%;display:flex;align-items:flex-end;padding:0;border:0;background:transparent;cursor:pointer}.bars i{display:block;width:100%;min-height:0;background:#3b82f6}.bars i.snow{background:#94a3b8}.bars i.other{background:#64748b}.minute-axis{display:flex;justify-content:space-between;color:#64748b;font-size:9px;font-variant-numeric:tabular-nums}.zero{padding-top:5px;color:#166534}.hour-strip{display:flex;gap:6px;overflow-x:auto;padding:4px 1px 8px;overscroll-behavior:contain}.hour-strip article{flex:0 0 102px;display:grid;justify-items:center;gap:4px;padding:8px 5px;border:1px solid #e2e8f0;border-radius:8px;background:#f8fafc;font-size:11px}.hour-strip article i{font-size:20px}.hour-strip time,.hour-strip b{font-variant-numeric:tabular-nums}.responsibility{margin-top:12px!important;padding:8px;border-radius:7px;background:#f1f5f9;color:#475569}.refer{display:flex;flex-wrap:wrap;gap:6px;padding-top:6px;color:#64748b;font-size:10px}@media(max-width:520px){.weather-popup{left:12px!important;right:12px;width:auto;max-height:52vh;transform:translateY(-100%)}}
</style>