import type { NationalAlarmSnapshot, ZhejiangAlarmDetail } from '../features/national-alarms/nationalAlarmTypes'

export class NationalAlarmApiError extends Error { readonly code: string; readonly status: number; constructor(code: string, status: number, message: string) { super(message); this.name = 'NationalAlarmApiError'; this.code = code; this.status = status } }
function object(value: unknown): Record<string, unknown> | null { return value !== null && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null }
function fail(response: Response, payload: unknown) { const root = object(payload), error = object(root?.error); throw new NationalAlarmApiError(typeof error?.code === 'string' ? error.code : 'NATIONAL_ALARM_REQUEST_FAILED', response.status, typeof error?.message === 'string' ? error.message : '浙江预警数据暂不可用') }
function validSnapshot(value: unknown): value is NationalAlarmSnapshot { const root = object(value); return Boolean(root && Array.isArray(root.items) && object(root.summary) && typeof root.fetchedAt === 'string' && typeof root.expiresAt === 'string' && typeof root.source === 'string' && root.items.every((item) => { const alarm = object(item); return alarm && typeof alarm.id === 'string' && typeof alarm.title === 'string' && alarm.provinceCode === '33' && typeof alarm.mappableInZhejiang === 'boolean' && object(alarm.mapLocation) })) }
function validDetail(value: unknown): value is ZhejiangAlarmDetail { const root = object(value); return Boolean(root && typeof root.id === 'string' && (typeof root.issuedAt === 'string' || root.issuedAt === null) && (typeof root.body === 'string' || root.body === null)) }
async function json(response: Response) { try { return await response.json() } catch { throw new NationalAlarmApiError('INVALID_RESPONSE', response.status, '预警数据响应格式异常') } }
export interface NationalAlarmApi { list(signal?: AbortSignal): Promise<NationalAlarmSnapshot>; refresh(signal?: AbortSignal): Promise<NationalAlarmSnapshot>; detail(id: string, signal?: AbortSignal): Promise<ZhejiangAlarmDetail> }
export function createNationalAlarmApi(fetchImpl: typeof fetch = globalThis.fetch): NationalAlarmApi { return {
  async list(signal) { const response = await fetchImpl('/api/national-weather-alarms', { headers: { accept: 'application/json' }, signal }); const payload = await json(response); if (!response.ok) fail(response, payload); if (!validSnapshot(payload)) throw new NationalAlarmApiError('INVALID_RESPONSE', response.status, '预警数据响应结构异常'); return payload },
  async refresh(signal) { const response = await fetchImpl('/api/national-weather-alarms/refresh', { method: 'POST', headers: { accept: 'application/json' }, signal }); const payload = await json(response); if (!response.ok) fail(response, payload); if (!validSnapshot(payload)) throw new NationalAlarmApiError('INVALID_RESPONSE', response.status, '预警数据响应结构异常'); return payload },
  async detail(id, signal) { const response = await fetchImpl(`/api/national-weather-alarms/${encodeURIComponent(id)}`, { headers: { accept: 'application/json' }, signal }); const payload = await json(response); if (!response.ok) fail(response, payload); if (!validDetail(payload)) throw new NationalAlarmApiError('INVALID_RESPONSE', response.status, '预警详情响应结构异常'); return payload },
} }
export const nationalAlarmApi = createNationalAlarmApi()
