import L from 'leaflet'
import type { AlertRegion, WeatherBundle, WeatherSelection } from '../features/weather/weatherTypes'
import { iconClass, sortAlerts, warningColor, warningForeground } from '../features/weather/weatherAdapter'
export const WEATHER_PANES={marker:{name:'weatherMarkerPane',zIndex:441},alert:{name:'weatherAlertPane',zIndex:442}} as const
export interface WeatherLayerCallbacks{onLocationClick?(kind:'default'|'picked',point:{x:number;y:number}):void;onAlertClick?(selection:WeatherSelection,point:{x:number;y:number}):void}
function esc(v:string){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!))}
export function buildAlertBadgeHtml(region:AlertRegion,alert:NonNullable<AlertRegion['alerts']>[number],selected:boolean){const color=warningColor(alert),foreground=warningForeground(alert),name=alert.eventType?.name||'天气预警',level=alert.color?.code||alert.severity||'预警';return`<button type="button" data-alert-id="${esc(alert.id)}" class="weather-alert-badge ${selected?'selected':''}" style="--warning:${esc(color)};--warning-fg:${foreground}" aria-label="${esc(region.name)} ${esc(name)} ${esc(level)}"><span class="weather-alert-main"><i class="${iconClass(alert.icon)}" aria-hidden="true"></i><b>${esc(name)}</b></span><span class="weather-alert-level">${esc(level)}</span></button>`}
export function buildAlertGroupHtml(region:AlertRegion,selection:WeatherSelection|null){const sorted=sortAlerts(region.alerts||[]);return`<div class="weather-alert-group-shell"><span class="weather-alert-scroll-hint start" aria-hidden="true">‹</span><div class="weather-alert-group" tabindex="0" role="group" aria-label="${esc(region.name)} ${sorted.length} 条天气预警">${sorted.map(alert=>buildAlertBadgeHtml(region,alert,selection?.contextCode===region.code&&selection.alertId===alert.id)).join('')}</div><span class="weather-alert-scroll-hint end" aria-hidden="true">›</span></div>`}
export function createWeatherLayerController(map:L.Map,callbacks:WeatherLayerCallbacks={}){
 for(const pane of Object.values(WEATHER_PANES)){const el=map.getPane(pane.name)??map.createPane(pane.name);el.style.zIndex=String(pane.zIndex)}
 const defaults=L.layerGroup().addTo(map),alerts=L.layerGroup().addTo(map);let defaultMarker:L.Marker|null=null,pickedMarker:L.Marker|null=null
 function point(e:L.LeafletMouseEvent){return{x:e.containerPoint.x,y:e.containerPoint.y}}
 function weatherIcon(bundle:WeatherBundle,kind:'default'|'picked'){const current=bundle.current.status==='success'?bundle.current.data:null,code=current?.condition.code,temp=current?.temperature.value,unit=current?.temperature.unit||'';const label=current?`${current.condition.text||'天气'}，${temp??'--'}${unit}`:'天气加载异常';return L.divIcon({className:`weather-marker-wrap ${kind}`,html:`<button type="button" class="weather-marker" aria-label="${esc(label)}"><i class="${iconClass(code)}" aria-hidden="true"></i><strong>${temp??'--'}${esc(unit)}</strong></button>`,iconSize:[72,36],iconAnchor:[36,36]})}
 function renderLoading(location:{lat:number;lon:number},kind:'default'|'picked'='default'){const marker=L.marker([location.lat,location.lon],{pane:WEATHER_PANES.marker.name,keyboard:true,bubblingMouseEvents:false,icon:L.divIcon({className:`weather-marker-wrap ${kind} loading`,html:'<button type="button" class="weather-marker" aria-label="天气加载中"><i class="qi-999" aria-hidden="true"></i><strong>--</strong></button>',iconSize:[72,36],iconAnchor:[36,36]})}).addTo(defaults).on('click',(e)=>{L.DomEvent.stopPropagation(e.originalEvent);callbacks.onLocationClick?.(kind,point(e))});if(kind==='picked'){pickedMarker?.remove();pickedMarker=marker}else{defaultMarker?.remove();defaultMarker=marker}}
 function renderDefault(bundle:WeatherBundle){defaultMarker?.remove();defaultMarker=L.marker([bundle.location.lat,bundle.location.lon],{pane:WEATHER_PANES.marker.name,icon:weatherIcon(bundle,'default'),keyboard:true,bubblingMouseEvents:false}).addTo(defaults).on('click',(e)=>{L.DomEvent.stopPropagation(e.originalEvent);callbacks.onLocationClick?.('default',point(e))})}
 function renderPicked(bundle:WeatherBundle){pickedMarker?.remove();pickedMarker=L.marker([bundle.originalLocation.lat,bundle.originalLocation.lon],{pane:WEATHER_PANES.marker.name,icon:weatherIcon(bundle,'picked'),keyboard:true,bubblingMouseEvents:false}).addTo(defaults).on('click',(e)=>{L.DomEvent.stopPropagation(e.originalEvent);callbacks.onLocationClick?.('picked',point(e))})}
 function clearPicked(){pickedMarker?.remove();pickedMarker=null}
 function renderAlerts(regions:readonly AlertRegion[],selection:WeatherSelection|null){alerts.clearLayers();for(const region of regions){const sorted=sortAlerts(region.alerts||[]);if(!sorted.length)continue;const marker=L.marker([region.point[1],region.point[0]],{pane:WEATHER_PANES.alert.name,keyboard:false,bubblingMouseEvents:false,icon:L.divIcon({className:'weather-alert-badge-wrap',html:buildAlertGroupHtml(region,selection),iconSize:[Math.min(292,sorted.length*94),74],iconAnchor:[Math.min(146,sorted.length*47),37]})}).addTo(alerts);marker.on('add',()=>{const element=marker.getElement();const group=element?.querySelector<HTMLElement>('.weather-alert-group');if(!group)return;group.addEventListener('keydown',(event)=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();group.scrollBy({left:event.key==='ArrowRight'?94:-94,behavior:'smooth'})}});for(const button of group.querySelectorAll<HTMLButtonElement>('[data-alert-id]'))button.addEventListener('click',(event)=>{event.stopPropagation();const p=map.latLngToContainerPoint(marker.getLatLng());callbacks.onAlertClick?.({contextCode:region.code,alertId:button.dataset.alertId!},{x:p.x,y:p.y})})})}}
 function clear(){defaults.clearLayers();alerts.clearLayers();defaultMarker=null;pickedMarker=null}
 return{renderLoading,renderDefault,renderPicked,clearPicked,renderAlerts,clear,destroy(){clear()}}
}
