import L from 'leaflet'
import type { AlertRegion, WeatherBundle, WeatherSelection } from '../features/weather/weatherTypes'
import { iconClass, sortAlerts, warningColor, warningForeground, warningLevelText } from '../features/weather/weatherAdapter'
export const WEATHER_PANES={marker:{name:'weatherMarkerPane',zIndex:455},alert:{name:'weatherAlertPane',zIndex:456}} as const
export interface WeatherLayerCallbacks{onLocationClick?(kind:'default'|'picked',point:{x:number;y:number}):void;onAlertClick?(selection:WeatherSelection,point:{x:number;y:number}):void}
function esc(v:string){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!))}
export function buildAlertBadgeHtml(region:AlertRegion,alert:NonNullable<AlertRegion['alerts']>[number],selected:boolean){const color=warningColor(alert),foreground=warningForeground(alert),name=alert.eventType?.name||'天气预警',level=warningLevelText(alert);return`<button type="button" data-alert-id="${esc(alert.id)}" class="weather-alert-badge ${selected?'selected':''}" style="--warning:${esc(color)};--warning-fg:${foreground}" aria-label="${esc(region.name)} ${esc(name)} ${esc(level)}"><span class="weather-alert-main"><i class="${iconClass(alert.icon)}" aria-hidden="true"></i><b>${esc(name)}</b></span><span class="weather-alert-level">${esc(level)}</span></button>`}
export function buildAlertGroupHtml(region:AlertRegion,selection:WeatherSelection|null){const sorted=sortAlerts(region.alerts||[]);return`<div class="weather-alert-group-shell"><span class="weather-alert-scroll-hint start" aria-hidden="true">‹</span><div class="weather-alert-group" tabindex="0" role="group" aria-label="${esc(region.name)} ${sorted.length} 条天气预警">${sorted.map(alert=>buildAlertBadgeHtml(region,alert,selection?.contextCode===region.code&&selection.alertId===alert.id)).join('')}</div><span class="weather-alert-scroll-hint end" aria-hidden="true">›</span></div>`}
export function createWeatherLayerController(map:L.Map,callbacks:WeatherLayerCallbacks={}){
 for(const pane of Object.values(WEATHER_PANES)){const el=map.getPane(pane.name)??map.createPane(pane.name);el.style.zIndex=String(pane.zIndex)}
 const defaults=L.layerGroup().addTo(map),alerts=L.layerGroup().addTo(map);let defaultMarker:L.Marker|null=null,pickedMarker:L.Marker|null=null
 function point(e:L.LeafletMouseEvent){return{x:e.containerPoint.x,y:e.containerPoint.y}}
 function temperatureRange(bundle:WeatherBundle,currentTemp:number|null|undefined,currentUnit:string){const items=bundle.hourly.status==='success'&&Array.isArray(bundle.hourly.data)?bundle.hourly.data:[];const temperatures=items.map(item=>item.temperature?.value).filter((value):value is number=>typeof value==='number'&&Number.isFinite(value));const unit=items.find(item=>item.temperature?.unit)?.temperature?.unit||currentUnit;const integer=(value:number)=>String(Math.round(value));if(temperatures.length)return `${integer(Math.max(...temperatures))}/${integer(Math.min(...temperatures))}${unit}`;return currentTemp==null?'--':`${integer(currentTemp)}${currentUnit}`}
 function weatherIcon(bundle:WeatherBundle,kind:'default'|'picked',placeName:string){const current=bundle.current.status==='success'?bundle.current.data:null,code=current?.condition.code,temp=current?.temperature.value,unit=current?.temperature.unit||'',failed=bundle.current.status==='error',condition=current?.condition.text||'天气',city=failed?'加载失败':placeName||'当前位置',range=temperatureRange(bundle,temp,unit),label=failed?'天气加载失败，点击查看详情和重试':`${city}，${condition}，最高${range.split('/')[0]}，最低${range.includes('/')?range.split('/')[1]:'--'}`;return L.divIcon({className:`weather-marker-wrap ${kind}${failed?' error':''}`,html:`<button type="button" class="weather-marker" aria-label="${esc(label)}"><span class="weather-marker-icon"><i class="${iconClass(code)}" aria-hidden="true"></i></span><span class="weather-marker-detail"><b>${esc(city)}</b><strong>${esc(range)}</strong></span></button>`,iconSize:[108,42],iconAnchor:[0,42]})}
 function renderStatus(location:{lat:number;lon:number},kind:'default'|'picked',status:'loading'|'error',placeName='当前位置'){const failed=status==='error',label=failed?'天气加载失败，点击查看详情和重试':'天气加载中',marker=L.marker([location.lat,location.lon],{pane:WEATHER_PANES.marker.name,keyboard:true,bubblingMouseEvents:false,icon:L.divIcon({className:`weather-marker-wrap ${kind} ${status}`,html:`<button type="button" class="weather-marker" aria-label="${label}"><span class="weather-marker-icon"><i class="qi-999" aria-hidden="true"></i></span><span class="weather-marker-detail"><b>${failed?'加载失败':esc(placeName||'当前位置')}</b><strong>--</strong></span></button>`,iconSize:[108,42],iconAnchor:[0,42]})}).addTo(defaults).on('click',(e)=>{L.DomEvent.stopPropagation(e.originalEvent);callbacks.onLocationClick?.(kind,point(e))});if(kind==='picked'){pickedMarker?.remove();pickedMarker=marker}else{defaultMarker?.remove();defaultMarker=marker}}
 function renderLoading(location:{lat:number;lon:number},kind:'default'|'picked'='default',placeName='当前位置'){renderStatus(location,kind,'loading',placeName)}
 function renderError(location:{lat:number;lon:number},kind:'default'|'picked'='default',placeName='当前位置'){renderStatus(location,kind,'error',placeName)}
 function renderDefault(bundle:WeatherBundle,placeName='当前位置'){defaultMarker?.remove();defaultMarker=L.marker([bundle.location.lat,bundle.location.lon],{pane:WEATHER_PANES.marker.name,icon:weatherIcon(bundle,'default',placeName),keyboard:true,bubblingMouseEvents:false}).addTo(defaults).on('click',(e)=>{L.DomEvent.stopPropagation(e.originalEvent);callbacks.onLocationClick?.('default',point(e))})}
 function renderPicked(bundle:WeatherBundle,placeName='当前位置'){pickedMarker?.remove();pickedMarker=L.marker([bundle.originalLocation.lat,bundle.originalLocation.lon],{pane:WEATHER_PANES.marker.name,icon:weatherIcon(bundle,'picked',placeName),keyboard:true,bubblingMouseEvents:false}).addTo(defaults).on('click',(e)=>{L.DomEvent.stopPropagation(e.originalEvent);callbacks.onLocationClick?.('picked',point(e))})}
 function clearPicked(){pickedMarker?.remove();pickedMarker=null}
 function clearLocation(){defaults.clearLayers();defaultMarker=null;pickedMarker=null}
 function renderAlerts(regions:readonly AlertRegion[],selection:WeatherSelection|null){alerts.clearLayers();for(const region of regions){const sorted=sortAlerts(region.alerts||[]);if(!sorted.length)continue;const marker=L.marker([region.point[1],region.point[0]],{pane:WEATHER_PANES.alert.name,keyboard:false,bubblingMouseEvents:false,icon:L.divIcon({className:'weather-alert-badge-wrap',html:buildAlertGroupHtml(region,selection),iconSize:[Math.min(292,sorted.length*94),74],iconAnchor:[Math.min(146,sorted.length*47),37]})}).addTo(alerts);marker.on('add',()=>{const element=marker.getElement();const group=element?.querySelector<HTMLElement>('.weather-alert-group');if(!group)return;group.addEventListener('keydown',(event)=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();group.scrollBy({left:event.key==='ArrowRight'?94:-94,behavior:'smooth'})}});for(const button of group.querySelectorAll<HTMLButtonElement>('[data-alert-id]'))button.addEventListener('click',(event)=>{event.stopPropagation();const p=map.latLngToContainerPoint(marker.getLatLng());callbacks.onAlertClick?.({contextCode:region.code,alertId:button.dataset.alertId!},{x:p.x,y:p.y})})})}}
 function clearAlerts(){alerts.clearLayers()}
 function clear(){clearLocation();clearAlerts()}
 return{renderLoading,renderError,renderDefault,renderPicked,clearPicked,clearLocation,renderAlerts,clearAlerts,clear,destroy(){clear()}}
}
