import { expect, test, type Page } from '@playwright/test'
import { cities, province } from './fixtures'

async function installFixtures(page: Page, options: { fixture?: 'failed'|'stale'|'request-error'|'address-unavailable' } = {}) {
  const requests: string[] = []
  await page.route('**/*', async (route) => {
    const url = new URL(route.request().url())
    if (url.pathname === '/data/boundary/province.geojson') return route.fulfill({ json: province })
    if (url.pathname === '/data/boundary/city/330000.geojson') return route.fulfill({ json: cities })
    if (url.pathname === '/data/rs.json') return route.fulfill({ status: 404, body: '' })
    if (url.pathname === '/api/weather') {
      requests.push(url.search)
      if (options.fixture) url.searchParams.set('fixture', options.fixture)
      return route.continue({ url: `http://127.0.0.1:4173${url.pathname}${url.search}` })
    }
    if (url.hostname.endsWith('tianditu.gov.cn')) return route.fulfill({ status: 204, body: '' })
    return route.continue()
  })
  return requests
}

async function openWeather(page: Page, waitForReady = true) {
  await page.goto('/')
  await page.getByRole('button', { name: '查看天气' }).click()
  await page.getByRole('button', { name: '实时天气' }).click()
  await expect(page.locator('.weather-marker')).toBeVisible()
  if(waitForReady)await expect(page.locator('.weather-marker-wrap.loading')).toHaveCount(0)
}

test('进入和退出天气保持地图视角，并恢复入口焦点', async ({ page }) => {
  await installFixtures(page)
  await page.goto('/')
  await expect(page.locator('.map-zoom-level')).toHaveText('Z 7.50')
  const before = await page.locator('.map-zoom-level').textContent()
  await page.getByRole('button', { name: '查看天气' }).click()
  await page.getByRole('button', { name: '实时天气' }).click()
  await expect(page.getByText('Ctrl', { exact: true })).toBeVisible()
  await expect(page.getByText('左键单击可以按点选查询天气')).toBeVisible()
  const weatherMarker = page.locator('.weather-marker')
  await expect(weatherMarker).toHaveAccessibleName(/浙江省.*小雨.*最高29.*最低26/)
  await expect(weatherMarker.locator('.weather-marker-icon')).toBeVisible()
  await expect(weatherMarker.locator('.weather-marker-detail b')).toHaveText('浙江省')
  await expect(weatherMarker.locator('.weather-marker-detail strong')).toHaveText('29/26°C')
  expect(await page.locator('.map-zoom-level').textContent()).toBe(before)
  await page.getByRole('button', { name: '当前：实时天气，点击切换' }).click()
  await page.getByRole('button', { name: '气象预警' }).click()
  await expect(page.getByRole('heading', { name: '气象预警', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '关闭浙江预警' }).click()
  await expect(page.getByRole('heading', { name: '气象预警', exact: true })).toBeHidden()
  await expect(page.getByRole('button', { name: '查看天气' })).toBeFocused()
  expect(await page.locator('.map-zoom-level').textContent()).toBe(before)
})

test('气象预警与实时天气模块互斥，实时天气保留完整位置浮窗', async ({ page }) => {
  await installFixtures(page)
  await openWeather(page)
  await expect(page.locator('.weather-panel')).toBeHidden()
  await page.locator('.weather-marker').click()
  const popup = page.getByRole('dialog', { name: '位置天气详情' })
  await expect(popup.locator('header strong')).toHaveText('实时天气')
  await expect(popup).toHaveClass(/(left|right)/)
  await expect(popup.locator('.query-context')).toHaveText('浙江省行政中心')
  await expect(popup.locator('.query-context')).not.toContainText(/°[NE]|\d+\.\d{2}/)
  await expect(popup.locator('.query-context')).toHaveCount(1)
  await expect(popup.locator('.refer')).toHaveCount(0)
  await expect(popup).toContainText('当前天气')
  await expect(popup).toContainText('未来两小时降水')
  await expect(popup).toContainText('未来 24 小时预报')
  await expect(popup.locator('.hour-strip article')).toHaveCount(24)
  await expect(popup.getByRole('button', { name: '查看后面的小时预报' })).toBeVisible()
  expect(await popup.locator('.hour-strip').evaluate((element) => getComputedStyle(element).scrollbarWidth)).toBe('none')
  await popup.getByRole('button', { name: '查看后面的小时预报' }).click()
  await expect.poll(() => popup.locator('.hour-strip').evaluate((element) => element.scrollLeft)).toBeGreaterThan(0)
  await expect(popup.getByRole('button', { name: '查看前面的小时预报' })).toBeVisible()
  await popup.getByRole('button', { name: '查看前面的小时预报' }).click()
  await expect.poll(() => popup.locator('.hour-strip').evaluate((element) => element.scrollLeft)).toBe(0)
  const weatherBeforeMove=await popup.boundingBox()
  await page.locator('.map').dragTo(page.locator('.map'),{sourcePosition:{x:420,y:340},targetPosition:{x:490,y:340}})
  await expect.poll(async()=>{const moved=await popup.boundingBox();return Boolean(weatherBeforeMove&&moved&&Math.abs(moved.x-weatherBeforeMove.x)>2)}).toBe(true)
  await page.locator('.map').click({position:{x:40,y:680}})
  await expect(popup).toBeHidden()
  await page.getByRole('button', { name: '当前：实时天气，点击切换' }).click()
  await page.getByRole('button', { name: '气象预警' }).click()
  await expect(page.locator('.weather-marker')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '气象预警', exact: true })).toBeVisible()
  await expect(page.locator('.national-alarm-panel .records button')).toHaveCount(1)
  const marker = page.locator('.national-alarm-marker')
  await expect(marker).toHaveCount(1)
  await marker.hover()
  await expect(page.getByRole('dialog', { name: '浙江预警详情' })).toBeHidden()
  await marker.click()
  const alert = page.getByRole('dialog', { name: '浙江预警详情' })
  await expect(alert).toContainText('杭州市发布暴雨红色预警')
  await expect(alert).not.toContainText('官方预警正文')
  await expect(alert).toContainText('预计未来三小时部分地区有强降雨')
  await expect(page.locator('.national-alarm-panel .records button.selected')).toHaveCount(1)
  await marker.click()
  await expect(alert).toBeHidden()
  await expect(page.locator('.national-alarm-panel .records button.selected')).toHaveCount(0)
  await marker.click()
  await expect(alert).toBeVisible()
  const beforeMove=await alert.boundingBox()
  await page.locator('.map').dragTo(page.locator('.map'),{sourcePosition:{x:420,y:340},targetPosition:{x:490,y:340}})
  await expect.poll(async()=>{const moved=await alert.boundingBox();return Boolean(beforeMove&&moved&&Math.abs(moved.x-beforeMove.x)>2)}).toBe(true)
  await page.locator('.map').click({position:{x:40,y:680}})
  await expect(alert).toBeHidden()
  await marker.click()
  await expect(alert).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(alert).toBeHidden()
  await expect(popup).toBeHidden()
})

test('地址增强失败时按层级路径降级且不泄露坐标', async ({ page }) => {
  await installFixtures(page, { fixture: 'address-unavailable' })
  await openWeather(page)
  await page.locator('.weather-marker').click()
  const popup = page.getByRole('dialog', { name: '位置天气详情' })
  await expect(popup.locator('header strong')).toHaveText('实时天气')
  await expect(popup.locator('.query-context')).toHaveText('浙江省')
  await expect(popup.locator('.query-context')).not.toContainText(/°[NE]|\d+\.\d{2}|代表点|附近/)

  await page.keyboard.press('Escape')
  await expect(popup).toBeHidden()
  await page.locator('.map').click({ position: { x: 500, y: 330 }, modifiers: ['Control'] })
  await expect(popup.locator('.query-context')).toHaveText('浙江省内地图点选位置')
  await expect(popup.locator('.query-context')).not.toContainText(/°[NE]|\d+\.\d{2}/)
})

test('1280x720 浮窗完整位于视口且保留可达标题栏与关闭按钮', async ({ page }) => {
  await page.setViewportSize({width:1280,height:720});await installFixtures(page);await openWeather(page);await page.locator('.weather-marker').click()
  const popup=page.getByRole('dialog',{name:'位置天气详情'}),box=await popup.boundingBox(),close=popup.getByRole('button',{name:'关闭天气浮窗'}),closeBox=await close.boundingBox()
  expect(box).not.toBeNull();expect(box!.x).toBeGreaterThanOrEqual(11);expect(box!.y).toBeGreaterThanOrEqual(11);expect(box!.x+box!.width).toBeLessThanOrEqual(1270);expect(box!.y+box!.height).toBeLessThanOrEqual(710)
  await expect(popup.locator('header')).toBeVisible();await expect(popup.locator('.popup-body')).toBeVisible();expect(closeBox).not.toBeNull();expect(closeBox!.x+closeBox!.width).toBeLessThanOrEqual(1280);expect(closeBox!.y+closeBox!.height).toBeLessThanOrEqual(720);const markerBox=await page.locator('.weather-marker').boundingBox();expect(markerBox).not.toBeNull();const overlaps=box!.x<markerBox!.x+markerBox!.width&&box!.x+box!.width>markerBox!.x&&box!.y<markerBox!.y+markerBox!.height&&box!.y+box!.height>markerBox!.y;expect(overlaps).toBe(false)
})

test('首次请求失败显示错误标记、失败浮窗和重试而非加载中',async({page})=>{await installFixtures(page,{fixture:'request-error'});await openWeather(page,false);const marker=page.locator('.weather-marker-wrap.error .weather-marker');await expect(marker).toHaveAccessibleName(/天气加载失败/);await expect(marker.locator('.weather-marker-detail b')).toHaveText('加载失败');await expect(marker.locator('.weather-marker-detail strong')).toHaveText('--');await marker.click();const popup=page.getByRole('dialog',{name:'位置天气详情'});await expect(popup).toContainText('位置天气加载失败');await expect(popup).toContainText('天气服务繁忙');await expect(popup).not.toContainText('正在加载新位置天气');await expect(popup.getByRole('button',{name:'重试'})).toBeVisible()})

test('stale 模块保留成功数据并分别显示上次成功时间和重试',async({page})=>{await installFixtures(page,{fixture:'stale'});await openWeather(page);await page.locator('.weather-marker').click();const popup=page.getByRole('dialog',{name:'位置天气详情'});await expect(popup.getByText(/实时天气更新失败，上次成功于/)).toBeVisible();await expect(popup.getByText(/未来两小时降水更新失败，上次成功于/)).toBeVisible();await expect(popup.getByText(/未来 24 小时预报更新失败，上次成功于/)).toBeVisible();await expect(popup.getByText('小雨 26 °C')).toBeVisible();await expect(popup.getByText('20分钟后降雨逐渐增强')).toBeVisible();await expect(popup.locator('.hour-strip article')).toHaveCount(24);await expect(popup.getByRole('button',{name:'重试'})).toHaveCount(3)})

test('Ctrl 点选仅刷新临时位置，Esc 恢复默认标记且不改变层级', async ({ page }) => {
  const requests = await installFixtures(page)
  await openWeather(page)
  await page.locator('.map').click({ position: { x: 500, y: 330 }, modifiers: ['Control'] })
  const popup = page.getByRole('dialog', { name: '位置天气详情' })
  await expect(popup.locator('.query-context')).toHaveText('杭州市西湖区测试点')
  await expect(popup.locator('.query-context')).not.toContainText('地图点选位置')
  expect(requests.filter((query) => query.includes('target=picked'))).toHaveLength(1)
  expect(requests.filter((query) => query.includes('target=picked'))[0]).not.toContain('key=')
  await page.keyboard.press('Escape')
  await expect(popup).toBeHidden()
  await expect(page.locator('.weather-panel')).toBeHidden()
  await expect(page.locator('.weather-marker-wrap.picked')).toHaveCount(0)
  await expect(page.locator('.weather-marker-wrap.default')).toHaveCount(1)
})

test('部分失败在 520px 视口保留成功模块与可达重试/关闭操作', async ({ page }) => {
  await page.setViewportSize({ width: 500, height: 760 })
  await installFixtures(page, { fixture: 'failed' })
  await openWeather(page)
  await page.locator('.weather-marker').click()
  const popup = page.getByRole('dialog', { name: '位置天气详情' })
  await expect(popup).toContainText('实时天气加载失败')
  await expect(popup).toContainText('未来两小时降水加载失败')
  await expect(popup).toContainText('未来 24 小时预报')
  const box = await popup.boundingBox()
  expect(box).not.toBeNull()
  expect(box!.x).toBeGreaterThanOrEqual(11)
  expect(box!.y).toBeGreaterThanOrEqual(11)
  expect(box!.x + box!.width).toBeLessThanOrEqual(490)
  expect(box!.y + box!.height).toBeLessThanOrEqual(750)
  const close=popup.getByRole('button', { name: '关闭天气浮窗' }),closeBox=await close.boundingBox()
  await expect(close).toBeVisible()
  expect(closeBox).not.toBeNull()
  expect(closeBox!.x).toBeGreaterThanOrEqual(0);expect(closeBox!.y).toBeGreaterThanOrEqual(0)
  expect(closeBox!.x+closeBox!.width).toBeLessThanOrEqual(500);expect(closeBox!.y+closeBox!.height).toBeLessThanOrEqual(760)
  await expect(page.getByRole('button', { name: '当前：实时天气，点击切换' })).toBeVisible()
})
