import {describe,expect,it} from 'vitest'
import { hourlyCards, iconClass, locationTitle, minutelyState, percentage, precipitationType, selectedAlert, sortAlertRegions, sortAlerts, weatherEnumZh } from './weatherAdapter'
import type { WeatherBundle, WeatherModule } from './weatherTypes'
const alert=(id:string,severity:string,time:string)=>({id,headline:id,issuedTime:time,urgency:null,severity,certainty:null,description:null,criteria:null,instruction:null,senderName:null,eventType:{name:'暴雨',code:'x'},icon:null,color:null})
describe('weather adapter',()=>{
 it('预警按严重度/时间排序且选择严格使用地区+id',()=>{const a=alert('same','Minor','2026-01-01'),b=alert('severe','Severe','2025-01-01');expect(sortAlerts([a,b]).map(x=>x.id)).toEqual(['severe','same']);const bundle={alerts:{status:'success',data:[{code:'a',name:'A',point:[120,30],status:'success',alerts:[a]},{code:'b',name:'B',point:[121,30],status:'success',alerts:[{...a,headline:'B'}]}]}} as unknown as WeatherBundle;expect(selectedAlert(bundle,{contextCode:'b',alertId:'same'})?.alert.headline).toBe('B');expect(sortAlertRegions(bundle.alerts.data)[0]?.code).toBe('a')})
 it('分钟四态、小时不补点/跨日升序',()=>{const base={data:null} as WeatherModule<any>;expect(minutelyState({...base,status:'error'})).toBe('error');expect(minutelyState({...base,status:'empty'})).toBe('empty');expect(minutelyState({status:'success',data:{updateTime:null,summary:null,refer:{sources:[],license:[]},minutely:[{fxTime:'2026-01-01',precip:0,type:'rain'}]}})).toBe('zero');expect(minutelyState({status:'success',data:{updateTime:null,summary:null,refer:{sources:[],license:[]},minutely:[{fxTime:'2026-01-01',precip:1,type:'snow'}]}})).toBe('data');const h=hourlyCards({status:'success',data:[{forecastTime:'2026-01-02T00:00:00+08:00'},{forecastTime:'2026-01-01T23:00:00+08:00'}] as any});expect(h.incomplete).toBe(true);expect(h.items[0]?.forecastTime).toContain('23:00')})
 it('严格格式与 fallback',()=>{expect(percentage(.865)).toBe('87%');expect(percentage(2)).toBe('--');expect(weatherEnumZh('Severe')).toBe('严重');expect(weatherEnumZh('new')).toBe('未知');expect(iconClass('100')).toBe('qi-100');expect(iconClass('bad')).toBe('qi-999');expect(precipitationType('snow')).toBe('雪');const bundle={target:'picked',address:{status:'error'}} as WeatherBundle;expect(locationTitle(bundle,'浙江省',false)).toBe('地图点选位置附近')})
})
