import {describe,expect,it} from 'vitest'
import { hourTimeLabel, hourlyCards, iconClass, locationTitle, minutelyState, moduleHasRefreshFailure, percentage, precipitationType, selectedAlert, sortAlertRegions, sortAlerts, temperatureText, warningColor, warningForeground, warningLevelText, weatherEnumZh } from './weatherAdapter'
import type { WeatherBundle } from './weatherTypes'
const alert=(id:string,severity:string,time:string)=>({id,headline:id,issuedTime:time,urgency:null,severity,certainty:null,description:null,criteria:null,instruction:null,senderName:null,eventType:{name:'暴雨',code:'x'},icon:null,color:null})
describe('weather adapter',()=>{
 it('预警按官方小写严重度/时间排序且选择严格使用地区+id',()=>{const a=alert('same','minor','2026-01-01'),b=alert('severe','severe','2025-01-01');expect(sortAlerts([a,b]).map(x=>x.id)).toEqual(['severe','same']);const bundle={alerts:{status:'success',data:[{code:'a',name:'A',point:[120,30],status:'success',alerts:[a]},{code:'b',name:'B',point:[121,30],status:'success',alerts:[{...a,headline:'B'}]}]}} as unknown as WeatherBundle;expect(selectedAlert(bundle,{contextCode:'b',alertId:'same'})?.alert.headline).toBe('B');expect(sortAlertRegions(bundle.alerts.data)[0]?.code).toBe('a')})
 it('分钟四态、小时不补点/跨日升序',()=>{expect(minutelyState({status:'error',error:{code:'x',message:'x'}})).toBe('error');expect(minutelyState({status:'empty',data:null,message:'none'})).toBe('empty');expect(minutelyState({status:'success',data:{updateTime:null,summary:null,refer:{sources:[],license:[]},minutely:[{fxTime:'2026-01-01',precip:0,type:'rain'}]}})).toBe('zero');expect(minutelyState({status:'success',data:{updateTime:null,summary:null,refer:{sources:[],license:[]},minutely:[{fxTime:'2026-01-01',precip:1,type:'snow'}]}})).toBe('data');const h=hourlyCards({status:'success',data:[{forecastTime:'2026-01-02T00:00:00+08:00'},{forecastTime:'2026-01-01T23:00:00+08:00'}] as any});expect(h.incomplete).toBe(true);expect(h.items[0]?.forecastTime).toContain('23:00')})
 it('严格格式、颜色对比与 fallback',()=>{expect(percentage(.865)).toBe('87%');expect(percentage(2)).toBe('--');expect(weatherEnumZh('severe')).toBe('严重');expect(weatherEnumZh('SEVERE')).toBe('严重');expect(weatherEnumZh('immediate')).toBe('立即');expect(weatherEnumZh('observed')).toBe('已观测');expect(weatherEnumZh('new')).toBe('未知');expect(iconClass('100')).toBe('qi-100');expect(iconClass('bad')).toBe('qi-999');expect(precipitationType('snow')).toBe('雪');const bundle={target:'picked',address:{status:'error'}} as WeatherBundle;expect(locationTitle(bundle,'浙江省',false)).toBe('地图点选位置附近');const yellow={...alert('a','minor',''),color:{code:'yellow',red:null,green:null,blue:null,alpha:null}};expect(warningColor(yellow)).toBe('#ca8a04');expect(warningForeground(yellow)).toBe('#0f172a');expect(warningLevelText(yellow)).toBe('黄色预警');expect(warningLevelText({...yellow,color:{...yellow.color,code:'mystery'},severity:'unexpected'})).toBe('天气预警')})
 it('气温取整显示，缺值回退',()=>{expect(temperatureText({value:26.6,unit:'°C'})).toBe('27 °C');expect(temperatureText({value:0,unit:'°C'})).toBe('0 °C');expect(temperatureText({value:-1.4,unit:'°C'})).toBe('-1 °C');expect(temperatureText(null)).toBe('--');expect(temperatureText({value:null,unit:'°C'})).toBe('--')})
 it('刷新失败和首项跨日标签明确',()=>{expect(moduleHasRefreshFailure({status:'success',data:{},stale:true,refreshError:{code:'x',message:'失败'}})).toBe(true);const tomorrow=new Date(Date.now()+86400000).toISOString();expect(hourTimeLabel(tomorrow,tomorrow,0)).toMatch(/\d{2}.*\d{2}/)})
})
